import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react';
import "reflect-metadata";
import { AppDataSource } from "../database/data-source"
import { User } from "../database/entity/User"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  AppDataSource.initialize().then(async () => {
    console.log("Inserting a new user into the database...")
    const user = new User()
    user.firstname = "Timber"
    user.lastname = "Saw"
    user.age = 25
    await AppDataSource.manager.save(user)
    console.log("Saved a new user with id: " + user.id)
    console.log("Loading users from the database...")
    const users = await AppDataSource.manager.find(User)
    console.log("Loaded users: ", users)
    console.log("Here you can setup and run express / fastify / any other framework.")
  }).catch(error => console.log(error))

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
